
# Add a resource on DB
POST http://localhost:3000/resources
Content-Type: application/json

{
  "name": "Example Resource 1",
  "audioPath": "path/to/audio.mp3",
  "videoUrl": "https://example.com/video1.mp4",
  "tags": [
    { "name": "Agro" },
    { "name": "Technology" }
  ]
}

###

GET http://localhost:3000/audio?v=OCNMMvE59sw

###

GET http://localhost:3000/audio?v=c5QktXTTIpU


###

GET http://localhost:3000/audio/translate

###

GET http://localhost:3000/audio/summary
