POST http://localhost:3000/
Content-Type: application/json

{
"title":"Evento 1",
"details":"Um evento para os apaixonados por TI.",
"maximumAttendees": 2
}

###

GET http://localhost:3000/audio?v=OCNMMvE59sw

###

GET http://localhost:3000/audio?v=c5QktXTTIpU


###

GET http://localhost:3000/audio/translate

###

GET http://localhost:3000/audio/summary
